### ISSUE TITLE
Make daily RFI thresholding script

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/hera_qm#251]
We've seen that broadcasting across all time for individual channels can lead to observation-length structure in the flags. OPM has some infrastructure for grabbing a full day (see smoothcal), so it should be fairly straightforward to grab a day of metrics, threshold, then save out to individual files.

**Comment by jsdillon** [comment]
I'd also add, we're seeing times that are almost 100% flagged due to the independence of the thresholding right now. This seems like something these daily RFI thresholds should be able to address:

![Screen Shot 2019-05-10 at 11 53 43 AM](https://user-images.githubusercontent.com/5281139/57561651-c663ab80-7341-11e9-9f41-32ccea96dcce.png)

**Comment by adampbeardsley** [comment]
Closed by #287.
