### ISSUE TITLE
UVFlag.weights_array set to all ones

### ISSUE THREAD

**Issue by mwilensky768** [HERA-Team/hera_qm#264]
The if block in line 146 of UVFlag (in __init__) sets the weights array to all ones regardless of the circumstance when not initializing from a file (link to if block below). Except in special circumstances, this is an erroneous weights array. I noticed this when I was trying to initialize one UVFlag object from another and made use of the weights arrays.

https://github.com/HERA-Team/hera_qm/blob/4485407ef8ce78d0adf60fec5474687c8427683b/hera_qm/uvflag.py#L146

**Comment by mwilensky768** [comment]
It looks like this was meant to be a default weights array when not initializing from a file, but it should not be the default weights array when initializing from another UVFlag object. It seems like it could be a reasonable default when initializing from a UVData object or UVCal object. I think this could be solved with adding

`and not isinstance(input, UVFlag)` to line 146

**Comment by adampbeardsley** [comment]
Hey Mike, this is a good catch. I would also just add that you don't want to hit this case if `input` is a list of `UVFlag` objects either. I _think_ we can solve this by replacing line 146 with:
`if issubclass(input.__class__, (UVData, UVCal)):`
does that sound right?

**Comment by mwilensky768** [comment]
What about the block on line 76 that initializes a `UVFlag` in waterfall using a `UVData` or `UVCal` object as input? If they have `copy_flags` set to `True`, does it make sense for the `weights_array` to be all ones? What about if they don't copy flags? I suppose if they don't copy flags, they have some data they are intending to fill the `metric_array` with anyway, and probably have the weights in mind, too.

Also, I feel like the result of that block on line 76 should be the same as initiating with `waterfall=False`, and then using the `to_waterfall()` method, but since the weights array at the end is all ones, the result ends up being different. Is that block necessary in light of `to_waterfall()`? If not,  I think if we get rid of the block at line 76, incorporate your proposed line, and add

`if waterfall:`
     `self.to_waterfall()`

at the end of `__init__()`, then it could all work.

**Comment by adampbeardsley** [comment]
Hmm, the more I look at this, I'm realizing the whole logic probably needs a good look. For example, if you pass `waterfall` and `copy_flags`, it just assumes you want to average the flags. But maybe you want to OR or AND the flags (which can be handled with `to_waterfall()`, but requires the `method` keyword. The if block at line 50 could also be replaced with a two liner to copy the object and append to the history. In fact, as it's currently written is probably a bug because it references the same objects for the arrays rather than copying them.

I think we need to make a matrix of what's passed in and what the expected behavior for various arrays is. I started a spreadsheet here:
https://docs.google.com/spreadsheets/d/1MErXCbrSb-3qFKpO2m4CICJznXB2B-Cy7c3OfGNn280/edit?usp=sharing

**Comment by adampbeardsley** [comment]
It's actually becoming clear that maybe we shouldn't have the `waterfall` option in init at all. But rather just have the user init then run `to_waterfall` themself. 
One problem with running `to_waterfall` instead of how it's currently written is that it would take a larger memory footprint to first make an object the size of the data, but then immediately reduce it.

**Comment by mwilensky768** [comment]
I don't really know where to begin on the spreadsheet, but it looks like how you filled it out you want the default `weights_array` with `waterfall=True` on a `UVData` input to be all ones. (Maybe you are actually just noting the current state of affairs??) I would expect the weights to be greater than 1 since we are combining information from multiple baselines here? Am I misunderstanding the `weights_array`?

**Comment by adampbeardsley** [comment]
I think this was fixed when we migrated over to pyuvdata (RadioAstronomySoftwareGroup/pyuvdata#560). Specifically, we removed the functionality to init one UVFlag with another in favor of doing an explicit copy.
@mwilensky768 do you agree this is fixed?

**Comment by mwilensky768** [comment]
Yes I'll close it.
